name: cl_media_viewers_flutter
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  material_design_icons_flutter: ^7.0.7296
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^5.0.0 
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
