name: colan_keepit
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cl_entity_viewers:
    path: ../cl_entity_viewers
  cl_media_viewers_flutter:
    path: ../cl_media_viewers_flutter
  collection: ^1.19.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_solidart: ^1.7.1
  http: ^1.3.0
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2808.0
  meta: ^1.15.0
  multi_split_view: ^3.6.0
  nsd: ^4.0.3
  server:
    path: ../server
  shadcn_ui:
    path: /Users/anandasarangaram/Work/flutter-shadcn-ui
  shared_preferences: ^2.5.2
  signals: ^6.0.2
  store_revised:
    path: ../store_revised

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/cloud_on_lan_128px_color.png
