name: api_tester
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_solidart: ^1.7.1
  http: ^1.3.0
  shadcn_ui:
    path: /Users/anandasarangaram/Work/flutter-shadcn-ui
  video_player: ^2.9.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
